<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';

/** The name of the database for WordPress */
define('DB_NAME', 'heroku_dfe0977515bac00');

/** MySQL database username */
define('DB_USER', 'b24a3a4bae493e');

/** MySQL database password */
define('DB_PASSWORD', '716d0794');

/** MySQL hostname */
define('DB_HOST', 'eu-cdbr-west-01.cleardb.com');

define('WP_ALLOW_REPAIR', true);